import type {
  FeatureSummary,
  NewsSummary,
  PhenomenonSummary,
  SchoolSummary,
} from "@/types/app";

/**
 * ★ 開発用のサンプルデータ（Phase 3 でDBに置き換える）★
 *
 * 学校名・戦績はすべて架空のもの。
 * 実在校の名前に架空の試合結果や甲子園出場歴を紐づけると、
 * 実在の学校について事実でない記録を作ることになるため、
 * デザイン確認用のデータでは実在校を使わない。
 */

const pref = (name: string, slug: string) => ({ name, slug });

export const SAMPLE_SCHOOLS: SchoolSummary[] = [
  {
    id: "s1",
    slug: "izumo-seiryo",
    name: "出雲西陵高校",
    officialName: "島根県立出雲西陵高等学校",
    prefecture: pref("島根", "shimane"),
    city: "出雲市",
    establishment: "prefectural",
    schoolKind: "high_school",
    catchcopy: "伝統と挑戦を胸に、新たな歴史をつくる。",
    image: null,
    koshienSpringCount: 2,
    koshienSummerCount: 3,
    lastKoshienYear: 2024,
  },
  {
    id: "s2",
    slug: "nagara-shogyo",
    name: "長良商業高校",
    officialName: "岐阜県立長良商業高等学校",
    prefecture: pref("岐阜", "gifu"),
    city: "岐阜市",
    establishment: "prefectural",
    schoolKind: "high_school",
    catchcopy: "商都の誇りを、グラウンドで。",
    image: null,
    koshienSpringCount: 4,
    koshienSummerCount: 6,
    lastKoshienYear: 2023,
  },
  {
    id: "s3",
    slug: "inaho-nogyo",
    name: "稲穂農業高校",
    officialName: "秋田県立稲穂農業高等学校",
    prefecture: pref("秋田", "akita"),
    city: "大仙市",
    establishment: "prefectural",
    schoolKind: "high_school",
    catchcopy: "土と汗が育てた、粘りの野球。",
    image: null,
    koshienSpringCount: 0,
    koshienSummerCount: 2,
    lastKoshienYear: 2022,
  },
  {
    id: "s4",
    slug: "konan-shogyo",
    name: "港南商業高校",
    officialName: "横浜市立港南商業高等学校",
    prefecture: pref("神奈川", "kanagawa"),
    city: "横浜市",
    establishment: "municipal",
    schoolKind: "high_school",
    catchcopy: "港町から、全国へ。",
    image: null,
    koshienSpringCount: 1,
    koshienSummerCount: 2,
    lastKoshienYear: 2021,
  },
  {
    id: "s5",
    slug: "aki-kawauchi",
    name: "安芸川内高校",
    officialName: "広島県立安芸川内高等学校",
    prefecture: pref("広島", "hiroshima"),
    city: "広島市",
    establishment: "prefectural",
    schoolKind: "high_school",
    catchcopy: "「人間力野球」で地域とともに、夢を追いかける。",
    image: null,
    koshienSpringCount: 3,
    koshienSummerCount: 4,
    lastKoshienYear: 2024,
  },
  {
    id: "s6",
    slug: "haebaru-sogo",
    name: "南風原総合高校",
    officialName: "沖縄県立南風原総合高等学校",
    prefecture: pref("沖縄", "okinawa"),
    city: "南風原町",
    establishment: "prefectural",
    schoolKind: "high_school",
    catchcopy: "南の島から全国へ。粘り強い野球が持ち味。",
    image: null,
    koshienSpringCount: 1,
    koshienSummerCount: 1,
    lastKoshienYear: 2020,
  },
  {
    id: "s7",
    slug: "tama-sakuragaoka",
    name: "多摩桜ヶ丘高校",
    officialName: "東京都立多摩桜ヶ丘高等学校",
    prefecture: pref("東京", "tokyo"),
    city: "八王子市",
    establishment: "prefectural",
    schoolKind: "high_school",
    catchcopy: "文武両道、都立の意地を見せる。",
    image: null,
    koshienSpringCount: 0,
    koshienSummerCount: 1,
    lastKoshienYear: 1998,
  },
  {
    id: "s8",
    slug: "tokachi-seiryu",
    name: "十勝清流高校",
    officialName: "北海道十勝清流高等学校",
    prefecture: pref("北海道", "hokkaido"),
    city: "帯広市",
    establishment: "prefectural",
    schoolKind: "high_school",
    catchcopy: "雪解けを待って、白球を追う。",
    image: null,
    koshienSpringCount: 0,
    koshienSummerCount: 2,
    lastKoshienYear: 2019,
  },
  {
    id: "s9",
    slug: "harima-kosen",
    name: "播磨工業高専",
    officialName: "播磨工業高等専門学校",
    prefecture: pref("兵庫", "hyogo"),
    city: "加古川市",
    establishment: "national",
    schoolKind: "kosen",
    catchcopy: "工学と野球、どちらも本気で。",
    image: null,
    koshienSpringCount: 0,
    koshienSummerCount: 0,
    lastKoshienYear: null,
  },
  {
    id: "s10",
    slug: "owari-kyoiku-fuzoku",
    name: "尾張教育大附属高校",
    officialName: "尾張教育大学教育学部附属高等学校",
    prefecture: pref("愛知", "aichi"),
    city: "名古屋市",
    establishment: "national",
    schoolKind: "high_school",
    catchcopy: "国立からの挑戦は、まだ終わらない。",
    image: null,
    koshienSpringCount: 0,
    koshienSummerCount: 1,
    lastKoshienYear: 1962,
  },
];

export const SAMPLE_NEWS: NewsSummary[] = [
  {
    id: "n1",
    slug: "izumo-seiryo-shimane-yusho-2024",
    title: "出雲西陵が逆転勝利で島根大会優勝！春の甲子園出場へ",
    summary:
      "九回二死からの一打で試合をひっくり返した。公立の出雲西陵が春の島根大会を制し、2年ぶりの甲子園出場を決めた。",
    category: "result",
    publishedAt: "2026-08-09T09:00:00+09:00",
    prefecture: pref("島根", "shimane"),
    image: null,
    sourceName: "公立応援団編集部",
  },
  {
    id: "n2",
    slug: "nagara-shogyo-best8",
    title: "長良商業が強豪私学を破りベスト8進出",
    summary:
      "投手陣の踏ん張りと堅い守備で、優勝候補を1点差で振り切った。公立勢では唯一のベスト8となる。",
    category: "result",
    publishedAt: "2026-08-08T18:30:00+09:00",
    prefecture: pref("岐阜", "gifu"),
    image: null,
    sourceName: "公立応援団編集部",
  },
  {
    id: "n3",
    slug: "natsu-chihou-taikai-kumiawase-2026",
    title: "2026年夏の地方大会 組み合わせ発表まとめ【随時更新】",
    summary:
      "全国47都道府県の夏の地方大会について、組み合わせが発表され次第まとめていく。公立校の初戦日程も併記する。",
    category: "news",
    publishedAt: "2026-08-07T12:00:00+09:00",
    prefecture: null,
    image: null,
    sourceName: "公立応援団編集部",
  },
  {
    id: "n4",
    slug: "renshu-kankyo-chiiki-torikumi",
    title: "公立高校野球部の練習環境を支える地域の取り組み",
    summary:
      "グラウンド整備や送迎、用具の寄付。限られた予算のなかで部を支える地域のかたちを取材した。",
    category: "topic",
    publishedAt: "2026-08-06T10:00:00+09:00",
    prefecture: pref("秋田", "akita"),
    image: null,
    sourceName: "公立応援団編集部",
  },
  {
    id: "n5",
    slug: "column-koritsu-de-yakyu-wo-tsuzukeru",
    title: "元公立高校球児が語る「公立で野球を続けるということ」",
    summary:
      "推薦もセレクションもない環境で、3年間をどう過ごしたか。卒業から10年が経った今、あらためて振り返ってもらった。",
    category: "column",
    publishedAt: "2026-08-05T08:00:00+09:00",
    prefecture: null,
    image: null,
    sourceName: "公立応援団編集部",
  },
  {
    id: "n6",
    slug: "harima-kosen-shoshutsujo",
    title: "播磨工業高専が兵庫大会で初戦突破 高専勢に注目",
    summary:
      "5年制の高専からも地方大会に挑むチームがある。授業と実習の合間を縫って練習を重ねてきた。",
    category: "topic",
    publishedAt: "2026-08-04T16:00:00+09:00",
    prefecture: pref("兵庫", "hyogo"),
    image: null,
    sourceName: "公立応援団編集部",
  },
];

export const SAMPLE_PHENOMENA: PhenomenonSummary[] = [
  {
    id: "p1",
    slug: "izumo-seiryo-2026-spring",
    title: "出雲西陵、県勢初の連覇で甲子園へ",
    year: 2026,
    season: "spring",
    level: "koshien",
    schoolName: "出雲西陵高校",
    prefecture: pref("島根", "shimane"),
    badge: "甲子園出場決定",
    image: null,
  },
  {
    id: "p2",
    slug: "nagara-shogyo-2026-spring",
    title: "長良商業、強豪私学を撃破しベスト8",
    year: 2026,
    season: "spring",
    level: "prefectural",
    schoolName: "長良商業高校",
    prefecture: pref("岐阜", "gifu"),
    badge: "ベスト8進出",
    image: null,
  },
  {
    id: "p3",
    slug: "inaho-nogyo-2026-spring",
    title: "稲穂農業、農業高校の意地で秋田大会優勝",
    year: 2026,
    season: "spring",
    level: "prefectural",
    schoolName: "稲穂農業高校",
    prefecture: pref("秋田", "akita"),
    badge: "注目",
    image: null,
  },
];

export const SAMPLE_FEATURES: FeatureSummary[] = [
  {
    id: "f1",
    slug: "chihou-taikai-kansen-guide",
    title: "地方大会の観戦をもっと楽しむために",
    subtitle: "球場の楽しみ方・持ち物・マナーも解説",
    category: "guide",
    image: null,
  },
  {
    id: "f2",
    slug: "rekidai-koritsu-senpu",
    title: "公立旋風を起こした名門たち",
    subtitle: "記憶に残るあの夏、あの戦い。",
    category: "history",
    image: null,
  },
  {
    id: "f3",
    slug: "zenkoku-koritsu-yakyubu",
    title: "全国の公立高校野球部紹介",
    subtitle: "それぞれの地域で輝く公立の姿へ。",
    category: "school_intro",
    image: null,
  },
  {
    id: "f4",
    slug: "kansen-goods",
    title: "高校野球観戦におすすめのグッズ",
    subtitle: "快適に、より楽しく観戦しよう。",
    category: "goods",
    image: null,
  },
];
